import { Section } from "../types";

const fleet: Section = {
  code: "fleet",
  name: "Fleet",
  name_ua: "Транспорт",
  description: "Fleet and transport management module.",
  description_ua: "Модуль управління автопарком і транспортом.",
  showInSidebar: true,
  showInMenu: true,
  allowedRoles: ["admin", "dispatcher", "mechanic"],
  icon: "CarOutlined",
  groups: [
    {
      code: "fleetmasterdata",
      groupName: "Master Data",
      groupName_ua: "Довідники",
      description: "Reference catalogs for vehicles, drivers, locations, and routes.",
      description_ua: "Довідники: транспорт, водії, пункти, маршрути.",
      showInSidebar: true,
      showInMenu: true,
      allowedRoles: ["admin", "dispatcher", "mechanic"],
      subgroups: [
        {
          code: "fleetoperational",
          subgroupName: "Operational Accounting",
          subgroupName_ua: "Оперативний облік",
          description: "Main transport master data.",
          description_ua: "Основні транспортні довідники.",
          showInSidebar: true,
          showInMenu: true,
          allowedRoles: ["admin", "dispatcher", "mechanic"],
          items: [
            {
              type: "MASTERDATA",
              code: "vehicles",
              name: "Vehicles",
              name_ua: "Автомобілі",
              description: "All company vehicles.",
              description_ua: "Усі автомобілі підприємства.",
              icon: "CarOutlined",
              hierarchy: true,
              formType: "customItem",
              subtables: [
                {
                  code: "odometerReadings",
                  name: "Odometer Readings",
                  name_ua: "Показання одометра",
                  description: "Vehicle odometer readings.",
                  description_ua: "Показання одометра по ТЗ.",
                  showInSidebar: false,
                  showInMenu: false,
                  allowedRoles: [],
                  autoload: false,
                  type: "related",
                },
                {
                  code: "vehicleComponent",
                  name: "Vehicle Components",
                  name_ua: "Комплектація ТЗ",
                  description: "Components assigned to vehicle.",
                  description_ua: "Комплектація та агрегати ТЗ.",
                  showInSidebar: false,
                  showInMenu: false,
                  allowedRoles: [],
                  autoload: false,
                  type: "related",
                },
              ],
              showInSidebar: true,
              showInMenu: true,
              allowedRoles: ["admin", "dispatcher", "mechanic"],
              printForms: [
                {
                  code: "main",
                  name: "Vehicle Card Print",
                  name_ua: "Друк картки ТЗ",
                  custom: true,
                  description: "Print form for vehicle card.",
                  description_ua: "Друк картки автомобіля.",
                  template: "VehicleCardPrint",
                },
              ],
            },
            {
              type: "MASTERDATA",
              code: "drivers",
              name: "Drivers",
              name_ua: "Водії",
              description: "Drivers list.",
              description_ua: "Довідник водіїв.",
              icon: "UserOutlined",
              hierarchy: false,
              formType: "default",
              subtables: [],
              showInSidebar: true,
              showInMenu: true,
              allowedRoles: ["admin", "dispatcher", "mechanic"],
              printForms: [],
            },
            {
              type: "MASTERDATA",
              code: "routes",
              name: "Routes",
              name_ua: "Маршрути",
              description: "Company transport routes.",
              description_ua: "Маршрути руху транспорту.",
              icon: "EnvironmentOutlined",
              hierarchy: false,
              formType: "default",
              subtables: [
                {
                  code: "routeWaypoints",
                  name: "Route Waypoints",
                  name_ua: "Точки маршруту",
                  description: "Waypoints for the route.",
                  description_ua: "Точки маршруту руху.",
                  showInSidebar: false,
                  showInMenu: false,
                  allowedRoles: [],
                  autoload: true,
                  type: "inline",
                },
              ],
              showInSidebar: true,
              showInMenu: true,
              allowedRoles: ["admin", "dispatcher"],
              printForms: [],
            },
            {
              type: "MASTERDATA",
              code: "locationpoints",
              name: "Location Points",
              name_ua: "Пункти призначення",
              description: "List of destinations.",
              description_ua: "Довідник пунктів призначення.",
              icon: "FlagOutlined",
              hierarchy: false,
              formType: "default",
              subtables: [],
              showInSidebar: true,
              showInMenu: true,
              allowedRoles: ["admin", "dispatcher"],
              printForms: [],
            },
            {
              type: "MASTERDATA",
              code: "countries",
              name: "Countries",
              name_ua: "Країни",
              description: "List of countries.",
              description_ua: "Довідник країн.",
              icon: "FlagOutlined",
              hierarchy: false,
              formType: "default",
              subtables: [],
              showInSidebar: true,
              showInMenu: true,
              allowedRoles: ["admin", "dispatcher"],
              printForms: [],
            },
          ],
        },
        {
          code: "maintenance",
          subgroupName: "Maintenance and Service",
          subgroupName_ua: "Ремонт та техобслуговування",
          description: "Maintenance types, components, repair units.",
          description_ua: "Види ТО, компоненти, агрегати.",
          showInSidebar: true,
          showInMenu: true,
          allowedRoles: ["admin", "mechanic"],
          items: [
            {
              type: "MASTERDATA",
              code: "maintenanceTypes",
              name: "Maintenance Types",
              name_ua: "Види ТО",
              description: "Types of vehicle maintenance.",
              description_ua: "Види технічного обслуговування.",
              icon: "ToolOutlined",
              hierarchy: false,
              formType: "default",
              subtables: [],
              showInSidebar: true,
              showInMenu: true,
              allowedRoles: ["admin", "mechanic"],
              printForms: [],
            },
            {
              type: "MASTERDATA",
              code: "transportComponents",
              name: "Transport Components",
              name_ua: "Компоненти ТЗ",
              description: "Vehicle components (e.g. tires, batteries).",
              description_ua: "Компоненти ТЗ (шини, акумулятори тощо).",
              icon: "DatabaseOutlined",
              hierarchy: false,
              formType: "default",
              subtables: [],
              showInSidebar: true,
              showInMenu: true,
              allowedRoles: ["admin", "mechanic"],
              printForms: [],
            },
            {
              type: "MASTERDATA",
              code: "repairUnits",
              name: "Repair Units",
              name_ua: "Агрегати",
              description: "Units for repair.",
              description_ua: "Агрегати для ремонту.",
              icon: "SettingOutlined",
              hierarchy: false,
              formType: "default",
              subtables: [],
              showInSidebar: true,
              showInMenu: true,
              allowedRoles: ["admin", "mechanic"],
              printForms: [],
            },
          ],
        },
        {
          code: "fuel",
          subgroupName: "Fuel Accounting",
          subgroupName_ua: "Облік ГСМ",
          description: "Fuel types catalog.",
          description_ua: "Довідник видів пального.",
          showInSidebar: true,
          showInMenu: true,
          allowedRoles: ["admin", "dispatcher"],
          items: [
            {
              type: "MASTERDATA",
              code: "fuelTypes",
              name: "Fuel Types",
              name_ua: "Типи пального",
              description: "Types of fuel used in fleet.",
              description_ua: "Види пального у автопарку.",
              icon: "FireOutlined",
              hierarchy: false,
              formType: "default",
              subtables: [],
              showInSidebar: true,
              showInMenu: true,
              allowedRoles: ["admin", "dispatcher"],
              printForms: [],
            },
          ],
        },
      ],
    },
    {
      code: "fleettransactions",
      groupName: "Transactions",
      groupName_ua: "Операції",
      description: "Fleet-related operational transactions.",
      description_ua: "Операції, пов'язані з автопарком.",
      showInSidebar: true,
      showInMenu: true,
      allowedRoles: ["admin", "dispatcher"],
      subgroups: [
        {
          code: "fleetoperationalTransactions",
          subgroupName: "Operational Transactions",
          subgroupName_ua: "Оперативні операції",
          description: "Waybills, orders, and invoices.",
          description_ua: "Путеві листи, замовлення, накладні.",
          showInSidebar: true,
          showInMenu: true,
          allowedRoles: ["admin", "dispatcher"],
          items: [
            {
              type: "TRANSACTIONDATA",
              code: "waybills",
              name: "Waybills",
              name_ua: "Путеві листи",
              description: "Waybill documents for fleet trips.",
              description_ua: "Путеві листи для рейсів автопарку.",
              icon: "FileTextOutlined",
              hierarchy: false,
              formType: "customBoth",
              subtables: [],
              showInSidebar: true,
              showInMenu: true,
              allowedRoles: ["admin", "dispatcher"],
              printForms: [
                {
                  code: "main",
                  name: "Waybill Print",
                  name_ua: "Друк путевого листа",
                  custom: true,
                  description: "Custom waybill print form.",
                  description_ua: "Кастомна форма друку путевого листа.",
                  template: "WaybillMainPrint",
                },
              ],
            },
            {
              type: "TRANSACTIONDATA",
              code: "orders",
              name: "Orders",
              name_ua: "Замовлення",
              description: "Fleet transport orders.",
              description_ua: "Замовлення на транспортні перевезення.",
              icon: "OrderedListOutlined",
              hierarchy: false,
              formType: "default",
              subtables: [],
              showInSidebar: true,
              showInMenu: true,
              allowedRoles: ["admin", "dispatcher"],
              printForms: [],
            },
            {
              type: "TRANSACTIONDATA",
              code: "transportInvoices",
              name: "Transport Invoices",
              name_ua: "Товарно-транспортні накладні",
              description: "Transport-related invoices.",
              description_ua: "Товарно-транспортні накладні.",
              icon: "FileSyncOutlined",
              hierarchy: false,
              formType: "default",
              subtables: [],
              showInSidebar: true,
              showInMenu: true,
              allowedRoles: ["admin", "dispatcher"],
              printForms: [],
            },
          ],
        },
        {
          code: "repair",
          subgroupName: "Repairs",
          subgroupName_ua: "Ремонт",
          description: "Maintenance and repair records.",
          description_ua: "Відомості про ремонти та ТО.",
          showInSidebar: true,
          showInMenu: true,
          allowedRoles: ["admin", "mechanic"],
          items: [
            {
              type: "TRANSACTIONDATA",
              code: "maintenanceRecords",
              name: "Maintenance Records",
              name_ua: "Ремонтні відомості",
              description: "Records of maintenance and repairs.",
              description_ua: "Відомості про проведення ремонтів і ТО.",
              icon: "ToolOutlined",
              hierarchy: false,
              formType: "default",
              subtables: [],
              showInSidebar: true,
              showInMenu: true,
              allowedRoles: ["admin", "mechanic"],
              printForms: [],
            },
          ],
        },
      ],
    },
    {
      code: "fleetanalytics",
      groupName: "Analytics",
      groupName_ua: "Аналітика",
      description: "Fleet analytics and reports.",
      description_ua: "Аналітика автопарку та звіти.",
      showInSidebar: true,
      showInMenu: true,
      allowedRoles: ["admin", "dispatcher"],
      subgroups: [
        {
          code: "fleetreports",
          subgroupName: "Reports",
          subgroupName_ua: "Звіти",
          description: "Key fleet reports.",
          description_ua: "Основні звіти по автопарку.",
          showInSidebar: true,
          showInMenu: true,
          allowedRoles: ["admin", "dispatcher"],
          items: [
            {
              type: "REPORT",
              code: "fuelMovement",
              name: "Fuel Movement Report",
              name_ua: "Відомість руху пального",
              description: "Fuel usage and movement analytics.",
              description_ua: "Аналітика руху та використання пального.",
              icon: "BarChartOutlined",
              hierarchy: false,
              formType: "default",
              subtables: [],
              showInSidebar: true,
              showInMenu: true,
              allowedRoles: ["admin", "dispatcher"],
              printForms: [],
            },
            {
              type: "REPORT",
              code: "transportStatistics",
              name: "Transport Statistics",
              name_ua: "Статистика роботи транспорту",
              description: "Fleet performance statistics.",
              description_ua: "Статистика роботи автотранспорту.",
              icon: "LineChartOutlined",
              hierarchy: false,
              formType: "default",
              subtables: [],
              showInSidebar: true,
              showInMenu: true,
              allowedRoles: ["admin", "dispatcher"],
              printForms: [],
            },
          ],
        },
      ],
    },
    {
      code: "fleetprocesses",
      groupName: "Processes",
      groupName_ua: "Процеси",
      description: "Fleet-related processes and tools.",
      description_ua: "Процеси й інструменти автопарку.",
      showInSidebar: true,
      showInMenu: true,
      allowedRoles: ["admin"],
      subgroups: [
        {
          code: "fleetservice",
          subgroupName: "Service Processes",
          subgroupName_ua: "Сервісні процеси",
          description: "Service and automation processes.",
          description_ua: "Сервісні та автоматизовані процеси.",
          showInSidebar: true,
          showInMenu: true,
          allowedRoles: ["admin"],
          items: [
            {
              type: "PROCESS",
              code: "kanbanBoard",
              name: "Kanban Board",
              name_ua: "Канбан-дошка",
              description: "Task board for fleet processes.",
              description_ua: "Канбан-дошка для завдань автопарку.",
              icon: "AppstoreOutlined",
              hierarchy: false,
              formType: "default",
              subtables: [],
              showInSidebar: true,
              showInMenu: true,
              allowedRoles: ["admin"],
              printForms: [],
            },
          ],
        },
      ],
    },
  ],
};

export default fleet;
