# Generated by Django 5.2 on 2025-05-14 09:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0004_organization_contract'),
        ('fleet', '0005_alter_vehicle_vehicle_type_order_routewaypoint_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogisticOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('distribution', 'Distribution'), ('collection', 'Collection')], max_length=20)),
                ('total_quantity', models.DecimalField(decimal_places=2, max_digits=12)),
                ('required_date', models.DateField()),
                ('transport_mode', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='planned', max_length=20)),
                ('comment', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.contract')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.organization')),
            ],
        ),
        migrations.CreateModel(
            name='LogisticLeg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=12)),
                ('transport_type', models.CharField(max_length=50)),
                ('planned_date', models.DateField()),
                ('actual_date', models.DateField(blank=True, null=True)),
                ('cost_estimate', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('cost_actual', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('assigned', 'Assigned'), ('completed', 'Completed')], default='planned', max_length=20)),
                ('from_location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='legs_from', to='core.locationpoint')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.item')),
                ('to_location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='legs_to', to='core.locationpoint')),
                ('vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='fleet.vehicle')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='legs', to='logistic.logisticorder')),
            ],
        ),
    ]
