# Generated by Django 5.2 on 2025-05-13 09:27

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(default=uuid.uuid4, editable=False, max_length=36, unique=True)),
                ('isfolder', models.BooleanField(default=False)),
                ('ismark', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=255)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[('M', 'Чоловік'), ('F', 'Жінка')], max_length=1, null=True)),
                ('license_number', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('ipn', models.CharField(max_length=20, unique=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='drivers_photos/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('comment', models.CharField(blank=True, default='', max_length=255)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='fleet.driver')),
            ],
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(default=uuid.uuid4, editable=False, max_length=36, unique=True)),
                ('isfolder', models.BooleanField(default=False)),
                ('ismark', models.BooleanField(default=False)),
                ('name', models.CharField(help_text="Назва маршруту (наприклад, 'Київ - Львів')", max_length=255)),
                ('code', models.CharField(blank=True, help_text='Унікальний код маршруту', max_length=50, null=True, unique=True)),
                ('distance_km', models.DecimalField(blank=True, decimal_places=1, help_text='Відстань у кілометрах', max_digits=6, null=True)),
                ('estimated_time_min', models.IntegerField(blank=True, help_text='Орієнтовний час у хвилинах', null=True)),
                ('comment', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('departure_point', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routes_from', to='core.locationpoint')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='fleet.route')),
                ('return_point', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routes_to', to='core.locationpoint')),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(default=uuid.uuid4, editable=False, max_length=36, unique=True)),
                ('isfolder', models.BooleanField(default=False)),
                ('ismark', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=255)),
                ('brand', models.CharField(max_length=255)),
                ('model', models.CharField(max_length=255)),
                ('year', models.IntegerField()),
                ('vin', models.CharField(max_length=100, unique=True)),
                ('license_plate', models.CharField(max_length=20)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='vehicles_photos/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('comment', models.CharField(blank=True, default='', max_length=255)),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicles', to='fleet.driver')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='fleet.vehicle')),
            ],
        ),
        migrations.CreateModel(
            name='Waybill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(default=uuid.uuid4, editable=False, max_length=36, unique=True)),
                ('ismark', models.BooleanField(default=False)),
                ('posted', models.BooleanField(default=False)),
                ('document_number', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('odometer_departure', models.PositiveIntegerField(verbose_name='Показник одометра при виїзді')),
                ('odometer_return', models.PositiveIntegerField(verbose_name='Показник одометра при поверненні')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waybills', to='fleet.driver')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waybills', to='fleet.vehicle')),
            ],
        ),
        migrations.CreateModel(
            name='OdometerReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(default=uuid.uuid4, editable=False, max_length=36, unique=True)),
                ('date', models.DateField(verbose_name='Дата показання')),
                ('odometer', models.PositiveIntegerField(verbose_name='Показання одометра')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='odometer_readings', to='fleet.vehicle')),
                ('waybill', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='odometer_readings', to='fleet.waybill')),
            ],
        ),
    ]
