# Generated by Django 5.2 on 2025-05-13 10:39

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransportComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(default=uuid.uuid4, editable=False, max_length=36, unique=True)),
                ('ismark', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('type', models.CharField(choices=[('tire', 'Шина'), ('battery', 'Акумулятор'), ('other', 'Інше')], max_length=20)),
                ('brand', models.CharField(blank=True, max_length=100, null=True)),
                ('serial', models.CharField(blank=True, max_length=100, null=True)),
                ('lifetime_months', models.PositiveIntegerField(blank=True, null=True, verbose_name='Строк служби (міс.)')),
                ('comment', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Компонент ТЗ',
                'verbose_name_plural': 'Компоненти ТЗ',
            },
        ),
    ]
