# Generated by Django 5.2 on 2025-05-13 10:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0002_transportcomponent'),
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('in_use', 'В роботі'), ('in_stock', 'На складі'), ('disposed', 'Списано')], default='in_use', max_length=20)),
                ('installed_at', models.DateField(blank=True, null=True)),
                ('comment', models.TextField(blank=True, default='')),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='fleet.transportcomponent')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='components', to='fleet.vehicle')),
            ],
            options={
                'verbose_name': 'Комплектуюча ТЗ',
                'verbose_name_plural': 'Комплектуючі ТЗ',
            },
        ),
    ]
