# Generated by Django 5.2 on 2025-05-13 10:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0003_vehiclecomponent'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='parent_vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attached_units', to='fleet.vehicle', verbose_name='Базовий ТЗ (для причепів)'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='vehicle_type',
            field=models.CharField(choices=[('car', 'Автомобіль'), ('trailer', 'Причіп'), ('equipment', 'Обладнання')], default='car', max_length=20, verbose_name='Тип ТЗ'),
        ),
    ]
