# Generated by Django 5.2 on 2025-05-13 11:43

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_itemcomponent'),
        ('fleet', '0004_vehicle_parent_vehicle_vehicle_vehicle_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='vehicle_type',
            field=models.CharField(choices=[('car', 'Автомобіль'), ('trailer', 'Причіп'), ('equipment', 'Обладнання')], default='car', max_length=20),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(default=uuid.uuid4, max_length=36, unique=True)),
                ('ismark', models.BooleanField(default=False)),
                ('posted', models.BooleanField(default=False)),
                ('customer', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('cargo_name', models.CharField(max_length=255)),
                ('cargo_weight', models.DecimalField(decimal_places=2, max_digits=10)),
                ('comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('route', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='fleet.route')),
            ],
            options={
                'verbose_name': 'Замовлення',
                'verbose_name_plural': 'Замовлення',
            },
        ),
        migrations.CreateModel(
            name='RouteWaypoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField()),
                ('comment', models.CharField(blank=True, max_length=255)),
                ('point', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.locationpoint')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waypoints', to='fleet.route')),
            ],
            options={
                'verbose_name': 'Проміжна точка',
                'verbose_name_plural': 'Проміжні точки',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='TransportInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(default=uuid.uuid4, max_length=36, unique=True)),
                ('ttn_number', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('sender', models.CharField(max_length=255)),
                ('recipient', models.CharField(max_length=255)),
                ('cargo_name', models.CharField(max_length=255)),
                ('cargo_weight', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(default='draft', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('arrival_point', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='arrival_transport_invoices', to='core.locationpoint')),
                ('departure_point', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='departure_transport_invoices', to='core.locationpoint')),
                ('driver', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='fleet.driver')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ttns', to='fleet.order')),
                ('vehicle', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='fleet.vehicle')),
            ],
            options={
                'verbose_name': 'Товарно-транспортна накладна',
                'verbose_name_plural': 'ТТН',
            },
        ),
    ]
