import { ItemType } from "./itemTypes";

// Schema version
export const schemaVersion = "1.0.3";

const sections = [
  {
    code: "fleet",
    name: "Fleet",
    name_ua: "Транспорт",
    showInSidebar: true,
    showInMenu: true,
    icon: "CarOutlined",
    groups: [
      {
        groupName: "Master Data",
        groupName_ua: "Довідники",
        subgroups: [
          {
            subgroupName: "Operational Accounting",
            subgroupName_ua: "Оперативний облік",
            items: [
              {
                type: ItemType.MASTERDATA,
                code: "vehicles",
                name: "Vehicles",
                name_ua: "Автомобілі",
                hierarchy: true,
                customForm: true,
                icon: "CarOutlined",
                subtables: [
                  {
                    code: "odometerReadings",
                    name: "Показання одометра",
                    name_ua: "Показання одометра",
                    autoload: false,
                    type: "related",
                  },
                  {
                    code: "VehicleComponent",
                    name: "VehicleComponent одометра",
                    name_ua: "Комплектация ТЗ",
                    autoload: false,
                    type: "related",
                  },
                ],
              },
              {
                type: ItemType.MASTERDATA,
                code: "drivers",
                name: "Drivers",
                name_ua: "Водії",
                hierarchy: false,
                icon: "UserOutlined",
              },
              {
                type: ItemType.MASTERDATA,
                code: "routes",
                name: "Routes",
                name_ua: "Маршрути",
                hierarchy: false,
                icon: "EnvironmentOutlined",
                subtables: [
                  {
                    code: "routeWaypoints",
                    name: "Точки маршруту",
                    name_ua: "Точки маршру",
                    autoload: true,
                    type: "inline",
                  },
                ],
              },
              {
                type: ItemType.MASTERDATA,
                code: "locationpoints",
                name: "Location points",
                name_ua: "Пункти призначення",
                hierarchy: false,
                icon: "FlagOutlined",
              },
              {
                type: ItemType.MASTERDATA,
                code: "countries",
                name: "Countries",
                name_ua: "Країни",
                hierarchy: false,
                icon: "FlagOutlined",
              },
            ],
          },
          {
            subgroupName: "Maintenance and Service",
            subgroupName_ua: "Ремонт та техобслуговування",
            items: [
              {
                type: ItemType.MASTERDATA,
                code: "maintenanceTypes",
                name: "Maintenance Types",
                name_ua: "Види ТО",
                hierarchy: false,
                icon: "ToolOutlined",
              },
              {
                type: ItemType.MASTERDATA,
                code: "transportComponents",
                name: "Transport Components",
                name_ua: "Компоненти ТЗ",
                icon: "DatabaseOutlined",
              },
              {
                type: ItemType.MASTERDATA,
                code: "repairUnits",
                name: "Repair Units",
                name_ua: "Агрегати",
                hierarchy: false,
                icon: "SettingOutlined",
              },
            ],
          },
          {
            subgroupName: "Fuel Accounting",
            subgroupName_ua: "Облік ГСМ",
            items: [
              {
                type: ItemType.MASTERDATA,
                code: "fuelTypes",
                name: "Fuel Types",
                name_ua: "Типи пального",
                hierarchy: false,
                icon: "FireOutlined",
              },
            ],
          },
        ],
      },
      {
        groupName: "Transactions",
        groupName_ua: "Операції",
        subgroups: [
          {
            subgroupName: "Operational Transactions",
            subgroupName_ua: "Оперативні операції",
            items: [
              {
                type: ItemType.TRANSACTIONDATA,
                code: "waybills",
                name: "Waybills",
                name_ua: "Путеві листи",
                customForm: true,
                icon: "FileTextOutlined",
              },
              {
                type: ItemType.TRANSACTIONDATA,
                code: "orders",
                name: "Orders",
                name_ua: "Замовлення",
                icon: "OrderedListOutlined",
              },
              {
                type: ItemType.TRANSACTIONDATA,
                code: "transportInvoices",
                name: "Transport Invoices",
                name_ua: "Товарно-транспортні накладні",
                icon: "FileSyncOutlined",
              },
            ],
          },
          {
            subgroupName: "Ремонт",
            subgroupName_ua: "Ремонт",
            items: [
              {
                type: ItemType.TRANSACTIONDATA,
                code: "maintenanceRecords",
                name: "Maintenance Records",
                name_ua: "Ремонтні відомості",
                customForm: false,
                icon: "ToolOutlined",
              },
            ],
          },
        ],
      },
      {
        groupName: "Analytics",
        groupName_ua: "Аналітика",
        subgroups: [
          {
            subgroupName: "Reports",
            subgroupName_ua: "Звіти",
            items: [
              {
                type: ItemType.REPORT,
                code: "fuelMovement",
                name: "Fuel Movement Report",
                name_ua: "Відомість руху пального",
                icon: "BarChartOutlined",
              },
              {
                type: ItemType.REPORT,
                code: "transportStatistics",
                name: "Transport Statistics",
                name_ua: "Статистика роботи транспорту",
                icon: "LineChartOutlined",
              },
            ],
          },
        ],
      },
      {
        groupName: "Processes",
        groupName_ua: "Процеси",
        subgroups: [
          {
            subgroupName: "Service Processes",
            subgroupName_ua: "Сервісні процеси",
            items: [
              {
                type: ItemType.PROCESS,
                code: "kanbanBoard",
                name: "Kanban Board",
                name_ua: "Канбан-дошка",
                icon: "AppstoreOutlined",
              },
            ],
          },
        ],
      },
    ],
  },
  {
    code: "logistic",
    name: "Logistics",
    name_ua: "Логістика",
    showInSidebar: true,
    showInMenu: true,
    icon: "ContainerOutlined",
    groups: [
      {
        groupName: "Transactions",
        groupName_ua: "Операції",
        subgroups: [
          {
            subgroupName: "Orders and Routes",
            subgroupName_ua: "Замовлення та маршрути",
            items: [
              {
                type: ItemType.TRANSACTIONDATA,
                code: "logisticOrders",
                name: "Logistic Orders",
                name_ua: "Логістичні задачі",
                icon: "OrderedListOutlined",
              },
              {
                type: ItemType.TRANSACTIONDATA,
                code: "routeSheets",
                name: "Route Sheets",
                name_ua: "Маршрутні листи",
                icon: "FileTextOutlined",
              },
            ],
          },
        ],
      },
      {
        groupName: "Analytics",
        groupName_ua: "Аналітика",
        subgroups: [
          {
            subgroupName: "Reports",
            subgroupName_ua: "Звіти",
            items: [
              {
                type: ItemType.REPORT,
                code: "logisticsPlanFact",
                name: "Plan vs Fact",
                name_ua: "План/Факт логістики",
                icon: "BarChartOutlined",
              },
            ],
          },
        ],
      },
    ],
  },
  {
    code: "essentials",
    name: "Essentials",
    name_ua: "Основи",
    showInSidebar: true,
    showInMenu: true,
    icon: "DollarOutlined",
    groups: [
      {
        groupName: "Master Data",
        groupName_ua: "Довідники",
        subgroups: [
          {
            subgroupName: "Goods Accounting",
            subgroupName_ua: "Облік товарів",
            items: [
              {
                type: ItemType.MASTERDATA,
                code: "items",
                name: "Items",
                name_ua: "Номенклатура",
                hierarchy: false,
                icon: "DropboxOutlined",
                subtables: [
                  {
                    code: "components",
                    name: "Комплектуючі",
                    name_ua: "Комплектуючі",
                    autoload: true,
                    type: "inline",
                  },
                ],
              },
              {
                type: ItemType.MASTERDATA,
                code: "units",
                name: "Units",
                name_ua: "Одиниці виміру",
                hierarchy: false,
                icon: "AppstoreOutlined",
              },
              {
                type: ItemType.MASTERDATA,
                code: "warehouses",
                name: "Warehouses",
                name_ua: "Склади",
                hierarchy: false,
                icon: "HomeOutlined",
              },
              {
                type: ItemType.MASTERDATA,
                code: "expenseItems",
                name: "Expense Items",
                name_ua: "Статті витрат",
                hierarchy: true,
                icon: "AccountBookOutlined",
              },
              {
                type: ItemType.MASTERDATA,
                code: "priceTypes",
                name: "Price Types",
                name_ua: "Види цін",
                hierarchy: false,
                icon: "DollarOutlined",
              },
            ],
          },
          {
            subgroupName: "Cash Accounting",
            subgroupName_ua: "Облік грошових коштів",
            items: [
              {
                type: ItemType.MASTERDATA,
                code: "currencies",
                name: "Currencies",
                name_ua: "Валюти",
                hierarchy: false,
                icon: "GlobalOutlined",
              },
              {
                type: ItemType.MASTERDATA,
                code: "cashboxes",
                name: "Cashboxes",
                name_ua: "Каси",
                hierarchy: false,
                icon: "WalletOutlined",
              },
              {
                type: ItemType.MASTERDATA,
                code: "banks",
                name: "Banks",
                name_ua: "Банки",
                hierarchy: false,
                icon: "BankOutlined",
              },
              {
                type: ItemType.MASTERDATA,
                code: "settlementaccounts",
                name: "Settlement Accounts",
                name_ua: "Розрахункові рахунки",
                hierarchy: false,
                icon: "CreditCardOutlined",
              },
            ],
          },
          {
            subgroupName: "Organizational Structure",
            subgroupName_ua: "Організаційна структура",
            items: [
              {
                type: ItemType.MASTERDATA,
                code: "clients",
                name: "Clients",
                name_ua: "Клієнти",
                hierarchy: false,
                icon: "TeamOutlined",
              },
              {
                type: ItemType.MASTERDATA,
                code: "businessOperations",
                name: "Business Operations",
                name_ua: "Господарські операції",
                hierarchy: false,
                icon: "AuditOutlined",
              },
              {
                type: ItemType.MASTERDATA,
                code: "chartOfAccounts",
                name: "Chart of Accounts",
                name_ua: "План рахунків",
                hierarchy: true,
                icon: "BookOutlined",
              },
              {
                type: ItemType.MASTERDATA,
                code: "organizations",
                name: "Organizations",
                name_ua: "Організації",
                hierarchy: false,
                icon: "ApartmentOutlined",
              },
              {
                type: ItemType.MASTERDATA,
                code: "contracts",
                name: "Contracts",
                name_ua: "Контракти",
                hierarchy: false,
                icon: "FileTextOutlined",
              },
              {
                type: ItemType.MASTERDATA,
                code: "departments",
                name: "Departments",
                name_ua: "Підрозділи",
                hierarchy: false,
                icon: "ClusterOutlined",
              },
              {
                type: ItemType.MASTERDATA,
                code: "persons",
                name: "Persons",
                name_ua: "Фізичні особи",
                hierarchy: false,
                icon: "IdcardOutlined",
              },
              {
                type: ItemType.MASTERDATA,
                code: "businessDirections",
                name: "Business Directions",
                name_ua: "Напрями діяльності",
                hierarchy: false,
                icon: "RadarChartOutlined",
              },
            ],
          },
        ],
      },
      {
        groupName: "Transactions",
        groupName_ua: "Операції",
        subgroups: [
          {
            subgroupName: "Sales",
            subgroupName_ua: "Продажі",
            items: [
              {
                type: ItemType.TRANSACTIONDATA,
                code: "invoices",
                name: "Invoices",
                name_ua: "Рахунки",
                hierarchy: false,
                icon: "ProfileOutlined",
              },
              {
                type: ItemType.TRANSACTIONDATA,
                code: "incomingPayments",
                name: "Incoming Payments",
                name_ua: "Надходження платежів",
                hierarchy: false,
                icon: "WalletOutlined",
              },
            ],
          },
          {
            subgroupName: "Internal Operations",
            subgroupName_ua: "Внутрішні операції",
            items: [
              {
                type: ItemType.TRANSACTIONDATA,
                code: "documentOperations",
                name: "Document Operations",
                name_ua: "Документ операція",
                hierarchy: false,
                icon: "FileProtectOutlined",
              },
            ],
          },
        ],
      },
      {
        groupName: "Analytics",
        groupName_ua: "Аналітика",
        subgroups: [
          {
            subgroupName: "Reports",
            subgroupName_ua: "Звіти",
            items: [
              {
                type: ItemType.REPORT,
                code: "profitAndLoss",
                name: "P&L",
                name_ua: "Звіт про прибутки та збитки",
                icon: "BarChartOutlined",
              },
              {
                type: ItemType.REPORT,
                code: "cashFlow",
                name: "Cash Flow",
                name_ua: "Звіт про рух грошових коштів",
                icon: "LineChartOutlined",
              },
              {
                type: ItemType.REPORT,
                code: "balanceSheet",
                name: "Balance Sheet",
                name_ua: "Баланс",
                icon: "PieChartOutlined",
              },
            ],
          },
        ],
      },
    ],
  },
  {
    code: "registers",
    name: "Registers",
    name_ua: "Реєстри",
    showInSidebar: true,
    showInMenu: true,
    icon: "DatabaseOutlined",
    groups: [
      {
        groupName: "Ledgers",
        groupName_ua: "Леджери",
        items: [
          {
            type: ItemType.LEDGER,
            code: "cashLedger",
            name: "Cash Ledger",
            name_ua: "Грошовий леджер",
            icon: "WalletOutlined",
          },
          {
            type: ItemType.LEDGER,
            code: "inventoryLedger",
            name: "Inventory Ledger",
            name_ua: "Леджер запасів",
            icon: "DropboxOutlined",
          },
        ],
      },
      {
        groupName: "Journals",
        groupName_ua: "Журнали",
        items: [
          {
            type: ItemType.JOURNAL,
            code: "cashJournal",
            name: "Cash Journal",
            name_ua: "Грошовий журнал",
            icon: "WalletOutlined",
          },
          {
            type: ItemType.JOURNAL,
            code: "inventoryJournal",
            name: "Inventory Journal",
            name_ua: "Журнал товарів",
            icon: "DropboxOutlined",
          },
        ],
      },
    ],
  },
  {
    code: "applications",
    name: "Applications",
    name_ua: "Додатки",
    showInSidebar: true,
    showInMenu: true,
    icon: "AppstoreOutlined",
    groups: [
      {
        groupName: "Applications",
        groupName_ua: "Додатки",
        items: [
          {
            type: ItemType.APPLICATOIN,
            code: "appEssentials",
            name: "Essentials",
            name_ua: "Основи",
            description:
              "Basic free module for managing organizations, accounts, clients, and documents",
            status: "installed",
            price: "free",
            icon: "DollarOutlined",
          },
          {
            type: ItemType.APPLICATOIN,
            code: "appFleet",
            name: "Fleet",
            name_ua: "Транспорт",
            description:
              "Module for managing fleet, drivers, routes, and operational costs",
            status: "activated",
            price: "free",
            icon: "CarOutlined",
          },
          {
            type: ItemType.APPLICATOIN,
            code: "appFleetTrack",
            name: "FleetTrack",
            name_ua: "FleetTrack",
            description:
              "Integration of fleet data with GPS tracking systems for real-time location, speed, routes, and telemetry",
            status: "available",
            price: "paid",
            link: "https://eswf.dev",
            icon: "RadarChartOutlined",
          },
          {
            type: ItemType.APPLICATOIN,
            code: "appDriverApp",
            name: "Driver App",
            name_ua: "Мобільний застосунок водія",
            description:
              "Mobile app for drivers: view routes, confirm deliveries, record mileage and fuel usage",
            status: "available",
            price: "paid",
            link: "https://eswf.dev",
            icon: "MobileOutlined",
          },
          {
            type: ItemType.APPLICATOIN,
            code: "appLogistic",
            name: "Logistic",
            name_ua: "Логістика",
            description:
              "Customer transport orders, cargo tracking, warehouses, and logistics",
            status: "available",
            price: "paid",
            link: "https://eswf.dev",
            icon: "ContainerOutlined",
          },
          {
            type: ItemType.APPLICATOIN,
            code: "appeTTN",
            name: "eTTN",
            name_ua: "е-ТТН",
            description: "Electronic waybills for cargo transportation (eTTN)",
            status: "available",
            price: "paid",
            link: "https://eswf.dev",
            icon: "FileSyncOutlined",
          },
          {
            type: ItemType.APPLICATOIN,
            code: "appAccounting",
            name: "Accounting",
            name_ua: "Бухгалтерія",
            description:
              "Accounting operations, balance sheets, cash flow, and reports",
            status: "available",
            price: "paid",
            link: "https://eswf.dev",
            icon: "CalculatorOutlined",
          },
          {
            type: ItemType.APPLICATOIN,
            code: "appMED",
            name: "M.E.Doc Integration",
            name_ua: "Інтеграція з M.E.Doc",
            description:
              "Module for exporting reports, invoices and signatures to M.E.Doc: seamless integration with electronic document flow",
            status: "available",
            price: "paid",
            link: "https://eswf.dev",
            icon: "FileDoneOutlined",
          },
          {
            type: ItemType.APPLICATOIN,
            code: "appBAFSync",
            name: "BAF Sync",
            name_ua: "BAF Обмін",
            description:
              "Exchange module for synchronizing data with external products on the BAF platform: documents, directories, and telemetry",
            status: "available",
            price: "paid",
            link: "https://eswf.dev",
            icon: "SyncOutlined",
          },
          {
            type: ItemType.APPLICATOIN,
            code: "appConsolidator",
            name: "Consolidator",
            name_ua: "Консолідація",
            description:
              "Module for consolidating financial, logistic and operational data across multiple organizations and databases",
            status: "available",
            price: "paid",
            link: "https://eswf.dev",
            icon: "BlockOutlined",
          },
          {
            type: ItemType.APPLICATOIN,
            code: "appCRM",
            name: "CRM",
            name_ua: "CRM",
            description:
              "Customer Relationship Management: leads, deals, contacts, tasks and communication",
            status: "available",
            price: "paid",
            link: "https://eswf.dev",
            icon: "ContactsOutlined",
          },
          {
            type: ItemType.APPLICATOIN,
            code: "appBudgeting",
            name: "Budgeting",
            name_ua: "Бюджетування",
            description:
              "Budget planning and control: define organizational budgets and monitor compliance with actual expenses",
            status: "available",
            price: "paid",
            link: "https://eswf.dev",
            icon: "CalculatorOutlined",
          },
          {
            type: ItemType.APPLICATOIN,
            code: "appPortal",
            name: "Client Portal",
            name_ua: "Особистий кабінет",
            description:
              "Secure client access to documents, orders, payments, and personal data",
            status: "available",
            price: "paid",
            link: "https://eswf.dev",
            icon: "UserSwitchOutlined",
          },
          {
            type: ItemType.APPLICATOIN,
            code: "appCommerce",
            name: "E-Commerce",
            name_ua: "Інтернет-магазин",
            description:
              "Online store integration: products, carts, orders, payments, delivery",
            status: "available",
            price: "paid",
            link: "https://eswf.dev",
            icon: "ShoppingCartOutlined",
          },
          {
            type: ItemType.APPLICATOIN,
            code: "appManager",
            name: "HR Manager",
            name_ua: "Управління персоналом",
            description:
              "Personnel management: work time tracking, payroll calculation, shifts and HR documents",
            status: "available",
            price: "paid",
            link: "https://eswf.dev",
            icon: "IdcardOutlined",
          },
          {
            type: ItemType.APPLICATOIN,
            code: "appChat",
            name: "ESWF Chat",
            name_ua: "Чат ESWF",
            description:
              "Internal team and client chat with GPT-powered assistant and notifications",
            status: "available",
            price: "paid",
            link: "https://eswf.dev",
            icon: "MessageOutlined",
          },
        ],
      },
    ],
  },
];

export default sections;
