import { Section, ItemType } from "../types";

const essentials: Section = {
  code: "essentials",
  name: "Essentials",
  name_ua: "Основи",
  description: "Base ERP module: organizations, accounts, clients, documents, reports.",
  description_ua: "Базовий модуль: організації, рахунки, контрагенти, документи, звіти.",
  showInSidebar: true,
  showInMenu: true,
  allowedRoles: ["admin", "accountant"],
  icon: "DollarOutlined",
  groups: [
    {
      code: "essentialsmasterdata",
      groupName: "Master Data",
      groupName_ua: "Довідники",
      description: "Reference data for essentials module.",
      description_ua: "Довідники базового модуля.",
      showInSidebar: true,
      showInMenu: true,
      allowedRoles: ["admin", "accountant"],
      subgroups: [
        {
          code: "goods",
          subgroupName: "Goods Accounting",
          subgroupName_ua: "Облік товарів",
          description: "Catalogs of goods, warehouses, prices, and expense items.",
          description_ua: "Каталоги товарів, складів, цін і статей витрат.",
          showInSidebar: true,
          showInMenu: true,
          allowedRoles: ["admin", "accountant"],
          items: [
            {
              type: "MASTERDATA",
              code: "items",
              name: "Items",
              name_ua: "Номенклатура",
              description: "List of all products and services.",
              description_ua: "Перелік усіх товарів і послуг.",
              icon: "DropboxOutlined",
              hierarchy: false,
              formType: "default",
              subtables: [
                {
                  code: "components",
                  name: "Components",
                  name_ua: "Комплектуючі",
                  description: "Component list for an item.",
                  description_ua: "Список комплектуючих для позиції номенклатури.",
                  showInSidebar: false,
                  showInMenu: false,
                  allowedRoles: [],
                  autoload: true,
                  type: "inline",
                },
              ],
              showInSidebar: true,
              showInMenu: true,
              allowedRoles: ["admin", "accountant"],
              printForms: [
                {
                  code: "main",
                  name: "Item List Print",
                  name_ua: "Друк списку номенклатури",
                  custom: false,
                  description: "Default print for the item list.",
                  description_ua: "Стандартний друк списку номенклатури.",
                  template: "UniversalMasterdataPrint",
                },
              ],
            },
            {
              type: "MASTERDATA",
              code: "units",
              name: "Units",
              name_ua: "Одиниці виміру",
              description: "Units of measurement directory.",
              description_ua: "Довідник одиниць виміру.",
              icon: "AppstoreOutlined",
              hierarchy: false,
              formType: "default",
              subtables: [],
              showInSidebar: true,
              showInMenu: true,
              allowedRoles: ["admin", "accountant"],
              printForms: [],
            },
            {
              type: "MASTERDATA",
              code: "warehouses",
              name: "Warehouses",
              name_ua: "Склади",
              description: "Storage locations directory.",
              description_ua: "Довідник складів.",
              icon: "HomeOutlined",
              hierarchy: false,
              formType: "default",
              subtables: [],
              showInSidebar: true,
              showInMenu: true,
              allowedRoles: ["admin", "accountant"],
              printForms: [],
            },
            {
              type: "MASTERDATA",
              code: "expenseItems",
              name: "Expense Items",
              name_ua: "Статті витрат",
              description: "Expense articles with hierarchical structure.",
              description_ua: "Довідник статей витрат із ієрархією.",
              icon: "AccountBookOutlined",
              hierarchy: true,
              formType: "default",
              subtables: [],
              showInSidebar: true,
              showInMenu: true,
              allowedRoles: ["admin", "accountant"],
              printForms: [],
            },
            {
              type: "MASTERDATA",
              code: "priceTypes",
              name: "Price Types",
              name_ua: "Види цін",
              description: "Price types for products and services.",
              description_ua: "Види цін для товарів та послуг.",
              icon: "DollarOutlined",
              hierarchy: false,
              formType: "default",
              subtables: [],
              showInSidebar: true,
              showInMenu: true,
              allowedRoles: ["admin", "accountant"],
              printForms: [],
            },
          ],
        },
        {
          code: "cash",
          subgroupName: "Cash Accounting",
          subgroupName_ua: "Облік грошових коштів",
          description: "Cash registers, banks, settlement accounts, and currencies.",
          description_ua: "Каси, банки, розрахункові рахунки та валюти.",
          showInSidebar: true,
          showInMenu: true,
          allowedRoles: ["admin", "accountant"],
          items: [
            {
              type: "MASTERDATA",
              code: "currencies",
              name: "Currencies",
              name_ua: "Валюти",
              description: "List of supported currencies.",
              description_ua: "Перелік підтримуваних валют.",
              icon: "GlobalOutlined",
              hierarchy: false,
              formType: "default",
              subtables: [],
              showInSidebar: true,
              showInMenu: true,
              allowedRoles: ["admin", "accountant"],
              printForms: [],
            },
            {
              type: "MASTERDATA",
              code: "cashboxes",
              name: "Cashboxes",
              name_ua: "Каси",
              description: "Cash register directory.",
              description_ua: "Довідник кас.",
              icon: "WalletOutlined",
              hierarchy: false,
              formType: "default",
              subtables: [],
              showInSidebar: true,
              showInMenu: true,
              allowedRoles: ["admin", "accountant"],
              printForms: [],
            },
            {
              type: "MASTERDATA",
              code: "banks",
              name: "Banks",
              name_ua: "Банки",
              description: "Directory of banks.",
              description_ua: "Довідник банків.",
              icon: "BankOutlined",
              hierarchy: false,
              formType: "default",
              subtables: [],
              showInSidebar: true,
              showInMenu: true,
              allowedRoles: ["admin", "accountant"],
              printForms: [],
            },
            {
              type: "MASTERDATA",
              code: "settlementaccounts",
              name: "Settlement Accounts",
              name_ua: "Розрахункові рахунки",
              description: "Company settlement accounts.",
              description_ua: "Розрахункові рахунки компанії.",
              icon: "CreditCardOutlined",
              hierarchy: false,
              formType: "default",
              subtables: [],
              showInSidebar: true,
              showInMenu: true,
              allowedRoles: ["admin", "accountant"],
              printForms: [],
            },
          ],
        },
        {
          code: "essentialsorg",
          subgroupName: "Organizational Structure",
          subgroupName_ua: "Організаційна структура",
          description: "Clients, business operations, chart of accounts, organizations, contracts, departments, persons, business directions.",
          description_ua: "Клієнти, операції, план рахунків, організації, контракти, підрозділи, особи, напрями діяльності.",
          showInSidebar: true,
          showInMenu: true,
          allowedRoles: ["admin", "accountant"],
          items: [
            {
              type: "MASTERDATA",
              code: "clients",
              name: "Clients",
              name_ua: "Клієнти",
              description: "Clients and contractors directory.",
              description_ua: "Довідник клієнтів і контрагентів.",
              icon: "TeamOutlined",
              hierarchy: false,
              formType: "default",
              subtables: [],
              showInSidebar: true,
              showInMenu: true,
              allowedRoles: ["admin", "accountant"],
              printForms: [],
            },
            {
              type: "MASTERDATA",
              code: "businessOperations",
              name: "Business Operations",
              name_ua: "Господарські операції",
              description: "Directory of business operations.",
              description_ua: "Довідник господарських операцій.",
              icon: "AuditOutlined",
              hierarchy: false,
              formType: "default",
              subtables: [],
              showInSidebar: true,
              showInMenu: true,
              allowedRoles: ["admin", "accountant"],
              printForms: [],
            },
            {
              type: "MASTERDATA",
              code: "chartOfAccounts",
              name: "Chart of Accounts",
              name_ua: "План рахунків",
              description: "Accounting chart with hierarchy.",
              description_ua: "Ієрархічний план рахунків.",
              icon: "BookOutlined",
              hierarchy: true,
              formType: "default",
              subtables: [],
              showInSidebar: true,
              showInMenu: true,
              allowedRoles: ["admin", "accountant"],
              printForms: [],
            },
            {
              type: "MASTERDATA",
              code: "organizations",
              name: "Organizations",
              name_ua: "Організації",
              description: "Legal entities and organizations.",
              description_ua: "Юридичні особи та організації.",
              icon: "ApartmentOutlined",
              hierarchy: false,
              formType: "default",
              subtables: [],
              showInSidebar: true,
              showInMenu: true,
              allowedRoles: ["admin", "accountant"],
              printForms: [],
            },
            {
              type: "MASTERDATA",
              code: "contracts",
              name: "Contracts",
              name_ua: "Контракти",
              description: "Client contracts and agreements.",
              description_ua: "Клієнтські контракти й угоди.",
              icon: "FileTextOutlined",
              hierarchy: false,
              formType: "default",
              subtables: [],
              showInSidebar: true,
              showInMenu: true,
              allowedRoles: ["admin", "accountant"],
              printForms: [],
            },
            {
              type: "MASTERDATA",
              code: "departments",
              name: "Departments",
              name_ua: "Підрозділи",
              description: "Organizational departments.",
              description_ua: "Підрозділи організації.",
              icon: "ClusterOutlined",
              hierarchy: false,
              formType: "default",
              subtables: [],
              showInSidebar: true,
              showInMenu: true,
              allowedRoles: ["admin", "accountant"],
              printForms: [],
            },
            {
              type: "MASTERDATA",
              code: "persons",
              name: "Persons",
              name_ua: "Фізичні особи",
              description: "Directory of persons and employees.",
              description_ua: "Довідник фізичних осіб та працівників.",
              icon: "IdcardOutlined",
              hierarchy: false,
              formType: "default",
              subtables: [],
              showInSidebar: true,
              showInMenu: true,
              allowedRoles: ["admin", "accountant"],
              printForms: [],
            },
            {
              type: "MASTERDATA",
              code: "businessDirections",
              name: "Business Directions",
              name_ua: "Напрями діяльності",
              description: "Business activity directions.",
              description_ua: "Напрями діяльності компанії.",
              icon: "RadarChartOutlined",
              hierarchy: false,
              formType: "default",
              subtables: [],
              showInSidebar: true,
              showInMenu: true,
              allowedRoles: ["admin", "accountant"],
              printForms: [],
            },
          ],
        },
      ],
    },
    // === Transactions ===
    {
      code: "essentialstransactions",
      groupName: "Transactions",
      groupName_ua: "Операції",
      description: "Sales, incoming payments, and internal operations.",
      description_ua: "Продажі, надходження платежів та внутрішні операції.",
      showInSidebar: true,
      showInMenu: true,
      allowedRoles: ["admin", "accountant"],
      subgroups: [
        {
          code: "sales",
          subgroupName: "Sales",
          subgroupName_ua: "Продажі",
          description: "Invoices and payment receipts.",
          description_ua: "Рахунки та надходження платежів.",
          showInSidebar: true,
          showInMenu: true,
          allowedRoles: ["admin", "accountant"],
          items: [
            {
              type: "TRANSACTIONDATA",
              code: "invoices",
              name: "Invoices",
              name_ua: "Рахунки",
              description: "Customer invoices.",
              description_ua: "Рахунки для клієнтів.",
              icon: "ProfileOutlined",
              hierarchy: false,
              formType: "default",
              subtables: [],
              showInSidebar: true,
              showInMenu: true,
              allowedRoles: ["admin", "accountant"],
              printForms: [],
            },
            {
              type: "TRANSACTIONDATA",
              code: "incomingPayments",
              name: "Incoming Payments",
              name_ua: "Надходження платежів",
              description: "Customer payment receipts.",
              description_ua: "Надходження оплат від клієнтів.",
              icon: "WalletOutlined",
              hierarchy: false,
              formType: "default",
              subtables: [],
              showInSidebar: true,
              showInMenu: true,
              allowedRoles: ["admin", "accountant"],
              printForms: [],
            },
          ],
        },
        {
          code: "essentialsinternal",
          subgroupName: "Internal Operations",
          subgroupName_ua: "Внутрішні операції",
          description: "Company document operations.",
          description_ua: "Документальні операції компанії.",
          showInSidebar: true,
          showInMenu: true,
          allowedRoles: ["admin", "accountant"],
          items: [
            {
              type: "TRANSACTIONDATA",
              code: "documentOperations",
              name: "Document Operations",
              name_ua: "Документ-операція",
              description: "Document-based business operations.",
              description_ua: "Господарські операції, оформлені документами.",
              icon: "FileProtectOutlined",
              hierarchy: false,
              formType: "default",
              subtables: [],
              showInSidebar: true,
              showInMenu: true,
              allowedRoles: ["admin", "accountant"],
              printForms: [],
            },
          ],
        },
      ],
    },
    // === Analytics ===
    {
      code: "essentialsanalytics",
      groupName: "Analytics",
      groupName_ua: "Аналітика",
      description: "Key financial and operational reports.",
      description_ua: "Ключові фінансові та операційні звіти.",
      showInSidebar: true,
      showInMenu: true,
      allowedRoles: ["admin", "accountant"],
      subgroups: [
        {
          code: "essentialsreports",
          subgroupName: "Reports",
          subgroupName_ua: "Звіти",
          description: "Standard financial statements.",
          description_ua: "Стандартні фінансові звіти.",
          showInSidebar: true,
          showInMenu: true,
          allowedRoles: ["admin", "accountant"],
          items: [
            {
              type: "REPORT",
              code: "profitAndLoss",
              name: "P&L",
              name_ua: "Звіт про прибутки та збитки",
              description: "Profit and loss statement.",
              description_ua: "Звіт про прибутки та збитки.",
              icon: "BarChartOutlined",
              hierarchy: false,
              formType: "default",
              subtables: [],
              showInSidebar: true,
              showInMenu: true,
              allowedRoles: ["admin", "accountant"],
              printForms: [],
            },
            {
              type: "REPORT",
              code: "cashFlow",
              name: "Cash Flow",
              name_ua: "Звіт про рух грошових коштів",
              description: "Cash flow statement.",
              description_ua: "Звіт про рух грошових коштів.",
              icon: "LineChartOutlined",
              hierarchy: false,
              formType: "default",
              subtables: [],
              showInSidebar: true,
              showInMenu: true,
              allowedRoles: ["admin", "accountant"],
              printForms: [],
            },
            {
              type: "REPORT",
              code: "balanceSheet",
              name: "Balance Sheet",
              name_ua: "Баланс",
              description: "Balance sheet statement.",
              description_ua: "Звіт Баланс.",
              icon: "PieChartOutlined",
              hierarchy: false,
              formType: "default",
              subtables: [],
              showInSidebar: true,
              showInMenu: true,
              allowedRoles: ["admin", "accountant"],
              printForms: [],
            },
          ],
        },
      ],
    },
  ],
};

export default essentials;
