# Generated by Django 5.2 on 2025-04-28 13:59

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driver',
            name='birth_year',
        ),
        migrations.AddField(
            model_name='driver',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='driver',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='driver',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='driver',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Чоловік'), ('F', 'Жінка')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='driver',
            name='ipn',
            field=models.CharField(default=1, max_length=20, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='driver',
            name='isfolder',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='driver',
            name='ismark',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='driver',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='core.driver'),
        ),
        migrations.AddField(
            model_name='driver',
            name='phone_number',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='driver',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='drivers_photos/'),
        ),
        migrations.AddField(
            model_name='driver',
            name='uuid',
            field=models.CharField(default=uuid.uuid4, editable=False, max_length=36, unique=True),
        ),
    ]
