# Generated by Django 5.2 on 2025-05-13 10:17

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(default=uuid.uuid4, editable=False, max_length=36, unique=True)),
                ('ismark', models.BooleanField(default=False)),
                ('isfolder', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=255, verbose_name='Найменування')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('type', models.CharField(choices=[('good', 'Товар'), ('service', 'Послуга'), ('kit', 'Комплект')], default='good', max_length=10)),
                ('unit', models.CharField(default='шт', max_length=20, verbose_name='Одиниця виміру')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('comment', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='core.item')),
            ],
            options={
                'verbose_name': 'Номенклатура',
                'verbose_name_plural': 'Номенклатура',
            },
        ),
    ]
