# Generated by Django 5.2 on 2025-05-03 13:16

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(default=uuid.uuid4, editable=False, max_length=36, unique=True)),
                ('isfolder', models.BooleanField(default=False)),
                ('ismark', models.BooleanField(default=False)),
                ('name', models.CharField(help_text="Назва маршруту (наприклад, 'Київ - Львів')", max_length=255)),
                ('code', models.CharField(blank=True, help_text='Унікальний код маршруту', max_length=50, null=True, unique=True)),
                ('distance_km', models.DecimalField(blank=True, decimal_places=1, help_text='Відстань у кілометрах', max_digits=6, null=True)),
                ('estimated_time_min', models.IntegerField(blank=True, help_text='Орієнтовний час у хвилинах', null=True)),
                ('comment', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('departure_point', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routes_from', to='core.locationpoint')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='core.route')),
                ('return_point', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routes_to', to='core.locationpoint')),
            ],
        ),
    ]
