# Generated by Django 5.2 on 2025-05-13 06:28

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_route'),
    ]

    operations = [
        migrations.CreateModel(
            name='Waybill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(default=uuid.uuid4, editable=False, max_length=36, unique=True)),
                ('ismark', models.BooleanField(default=False)),
                ('posted', models.BooleanField(default=False)),
                ('document_number', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('odometer_departure', models.PositiveIntegerField(verbose_name='Показник одометра при виїзді')),
                ('odometer_return', models.PositiveIntegerField(verbose_name='Показник одометра при поверненні')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waybills', to='core.driver')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waybills', to='core.vehicle')),
            ],
        ),
        migrations.CreateModel(
            name='OdometerReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(default=uuid.uuid4, editable=False, max_length=36, unique=True)),
                ('date', models.DateField(verbose_name='Дата показання')),
                ('odometer', models.PositiveIntegerField(verbose_name='Показання одометра')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='odometer_readings', to='core.vehicle')),
                ('waybill', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='odometer_readings', to='core.waybill')),
            ],
        ),
    ]
