# Generated by Django 5.2 on 2025-05-13 10:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_item'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=3, default=1.0, max_digits=10)),
                ('comment', models.CharField(blank=True, default='', max_length=255)),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='used_in_kits', to='core.item')),
                ('parent_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='components', to='core.item')),
            ],
            options={
                'verbose_name': 'Комплектуюча позиція',
                'verbose_name_plural': 'Комплектуючі позиції',
            },
        ),
    ]
