# Generated by Django 5.2 on 2025-05-15 07:00

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_organization_contract'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessOperation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(default=uuid.uuid4, editable=False, max_length=36, unique=True)),
                ('ismark', models.BooleanField(default=False)),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Код операції')),
                ('name', models.CharField(max_length=255, verbose_name='Назва операції')),
                ('description', models.TextField(blank=True, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Господарська операція',
                'verbose_name_plural': 'Господарські операції',
            },
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(default=uuid.uuid4, editable=False, max_length=36, unique=True)),
                ('ismark', models.BooleanField(default=False)),
                ('code', models.CharField(max_length=3, unique=True, verbose_name='Код (UAH, USD, EUR)')),
                ('name', models.CharField(max_length=50, verbose_name='Назва валюти')),
                ('symbol', models.CharField(blank=True, max_length=5, null=True, verbose_name='Символ (₴, $, €)')),
                ('rate', models.DecimalField(decimal_places=4, default=1.0, max_digits=12, verbose_name='Курс до базової')),
                ('comment', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Валюта',
                'verbose_name_plural': 'Валюти',
            },
        ),
        migrations.CreateModel(
            name='ChartOfAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(default=uuid.uuid4, editable=False, max_length=36, unique=True)),
                ('isfolder', models.BooleanField(default=True)),
                ('ismark', models.BooleanField(default=False)),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Код рахунку')),
                ('name', models.CharField(max_length=255, verbose_name='Назва рахунку')),
                ('comment', models.TextField(blank=True, null=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='core.chartofaccount')),
            ],
            options={
                'verbose_name': 'План рахунків',
                'verbose_name_plural': 'План рахунків',
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(default=uuid.uuid4, editable=False, max_length=36, unique=True)),
                ('isfolder', models.BooleanField(default=False)),
                ('ismark', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=255, verbose_name='Назва клієнта')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('tax_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='ІПН')),
                ('address', models.TextField(blank=True, null=True)),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='core.client')),
            ],
            options={
                'verbose_name': 'Клієнт',
                'verbose_name_plural': 'Клієнти',
            },
        ),
    ]
